package internal

import (
	"bytes"
	"html/template"
)

const baseTemplate = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{.Title}}</title>
</head>
<body>
<header><h1>{{.Title}}</h1></header>
<main>
{{.Content}}
</main>
<footer><p>Generated by SSG</p></footer>
</body>
</html>`

type PageData struct {
	Title   string
	Content template.HTML
}

func ApplyTemplate(title, content string) (string, error) {
	tmpl, err := template.New("base").Parse(baseTemplate)
	if err != nil {
		return "", err
	}
	data := PageData{
		Title:   title,
		Content: template.HTML(content),
	}
	var buf bytes.Buffer
	err = tmpl.Execute(&buf, data)
	if err != nil {
		return "", err
	}
	return buf.String(), nil
}
